### ISSUE TITLE
Cannot save keras model with tensorflow lattice layers

### ISSUE THREAD

**Issue by devavratTomar** [tensorflow/lattice#47] opened 2020-04-03 00:40 UTC
Saving the model having keras tfl layers creates the following problem.

`/usr/local/lib/python3.6/dist-packages/h5py/_hl/group.py in __setitem__(self, name, obj)
    371 
    372             if isinstance(obj, HLObject):
--> 373                 h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
    374 
    375             elif isinstance(obj, SoftLink):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.link()

RuntimeError: Unable to create link (name already exists)`

The error is reproduced in the colab example here.
https://colab.research.google.com/drive/1tknejj9CtM27bHGktsZSTnvLvH3eCgG8

**Comment by wbakst** [comment] 2020-04-07 20:26
Hi!
I looked through the colab that you linked but couldn't find any instances of model saving. Could you post a screenshot or code snippet that is causing the error so I can try to reproduce it on my end and see what's going on?

**Comment by devavratTomar** [comment] 2020-04-10 09:42
Hi, Sorry I tried to debug the problem. The error is now reproducible on the colab. 
![image](https://user-images.githubusercontent.com/29230157/78981502-5563df80-7b20-11ea-9b88-82ca2ea06ffc.png)
![image](https://user-images.githubusercontent.com/29230157/78981527-63196500-7b20-11ea-8c6b-c96b0fe11d0f.png)

**Comment by devavratTomar** [comment] 2020-04-10 09:45
I think the problem is that we give same name to the weights for all the instances of a layer. That's why h5 complains that the key is already present while saving the weights

**Comment by devavratTomar** [comment] 2020-04-10 09:48
https://github.com/tensorflow/lattice/blob/master/tensorflow_lattice/python/pwl_calibration_layer.py#L34

The names of weights are the same for all layers.

**Comment by wbakst** [comment] 2020-04-10 23:59
This is indeed the case. Thank you for pointing this out! I am going to work on a fix now.

**Comment by mmilanifard** [comment] 2020-04-13 17:49
Thanks for reporting the issue. Turns out we should not explicitly call the inner layer .build() during the build for the ParallelCombination layer. The next release will fix this issue.

**Comment by mmilanifard** [comment] 2020-04-14 23:26
Fixed in 2.0.4.

**Closed by mmilanifard** 2020-04-14 23:26 UTC
